language: go
go:
  - "1.8"  

branches:
  only:
    - blog

install:
  - wget -q -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.62.0/hugo_0.62.0_Linux-64bit.deb
  - sudo dpkg -i hugo.deb

script:
  - hugo

deploy:
  provider: pages
  local_dir: public
  target_branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  fqdn: zhangsiqi.me
  on:
    branch: blog